# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c3a77e4025c91a03811f9b7702a978825bcaa0cb5f2b35a0656ad3cc8d7070fbbad4a8717521394a45eb35c664c5d42744d82f51d441f4d62152e3f1a061417

test:
  secret_key_base: cdb004715fced7a07fcc821ba1eb61d5b0b008475cfed41dc650b5fa0976c809a95f941915ec5875981f2c26325a80cbba2774b251952d87fe4e9579646cada0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
